#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
kind: Deployment
apiVersion: apps/v1
metadata:
  name: orders
  labels:
    component: sockshop
spec:
  template:
    spec:
      containers:
        - name: orders
          image: helidonsockshop/orders-redis:2.0.0
